FROM node
WORKDIR /app
COPY package.json ./
RUN npm install  --legacy-peer-deps
COPY . .
RUN npm run build 
EXPOSE 3000
CMD [ "node", "dist/main" ]
# Étape d'exécution
# FROM node:21
# WORKDIR /Users/djigasalane/Documents/Personnel/sen_resto_plateform/backend/docker
# COPY --from=build dist ./dist
# COPY --from=build node_modules ./node_modules
# COPY --from=build package.json ./package.json
# EXPOSE 3000
# CMD ["node", "dist/src/main"]
