export enum PathRouter{
     coorporate='coorporate',
     banner='banner',
      establishmentType="establishment_type",
     gift='gift',
     transaction='transaction',
     cardAllocation='card_allocation',
     create='create',
     edit='edit/:id',
     list='list',
     default='',
     details='details/:id',
     delete= 'delete',
     story='story',
     city='city',
}